use mike;

-- MySQL Script generated by MySQL Workbench
-- 05/19/15 12:23:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema online_judge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online_judge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_judge` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `online_judge` ;

-- -----------------------------------------------------
-- Table `online_judge`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `aliasUsuario` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `paterno` VARCHAR(45) NOT NULL,
  `materno` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_judge`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`docente` (
  `idUsuario` INT NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  INDEX `idUSUARIO_idx` (`idUsuario` ASC),
  CONSTRAINT `idUSUARIO`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `online_judge`.`Usuarios` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_judge`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`materia` (
  `idmateria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `creditos` INT NOT NULL,
  `idDocente` INT NOT NULL,
  PRIMARY KEY (`idmateria`),
  INDEX `idDocente_idx` (`idDocente` ASC),
  CONSTRAINT `idDocente`
    FOREIGN KEY (`idDocente`)
    REFERENCES `online_judge`.`docente` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_judge`.`examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`examen` (
  `idexamen` INT NOT NULL AUTO_INCREMENT,
  `rutaArchivo` VARCHAR(255) NOT NULL,
  `unidad` VARCHAR(45) NOT NULL,
  `fechaAplicacion` DATE NOT NULL,
  `horaInicio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `horaFin` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idMateria` INT NOT NULL,
  `EstadoExamen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idexamen`),
  INDEX `idMateria_idx` (`idMateria` ASC),
  CONSTRAINT `idMateria`
    FOREIGN KEY (`idMateria`)
    REFERENCES `online_judge`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_judge`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`alumno` (
  `idUsuario` INT NOT NULL,
  `nControl` VARCHAR(45) NOT NULL,
  INDEX `iduser_idx` (`idUsuario` ASC),
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `iduser`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `online_judge`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_judge`.`Evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`Evaluacion` (
  `idAlumno` INT NOT NULL,
  `rutaSolucion` VARCHAR(255) NOT NULL,
  `idExamen` INT NOT NULL,
  `horaTermino` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `nota` DOUBLE NOT NULL DEFAULT 0.0,
  `fecha` DATE NOT NULL,
  `semestre` INT NOT NULL,
  INDEX `IDexamen_idx` (`idExamen` ASC),
  INDEX `fk_Evaluacion_alumno1_idx` (`idAlumno` ASC),
  PRIMARY KEY (`idAlumno`, `fecha`),
  CONSTRAINT `IDexamen`
    FOREIGN KEY (`idExamen`)
    REFERENCES `online_judge`.`examen` (`idexamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluacion_alumno1`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `online_judge`.`alumno` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_judge`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`proyecto` (
  `idproyecto` INT NOT NULL AUTO_INCREMENT,
  `rutaProyecto` VARCHAR(255) NOT NULL,
  `complejidad` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `idDocente` INT NOT NULL,
  PRIMARY KEY (`idproyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_judge`.`solucionProyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`solucionProyecto` (
  `idsolucionProyecto` INT NOT NULL AUTO_INCREMENT,
  `rutaSolucionProyecto` VARCHAR(255) NOT NULL,
  `idUsuarioEnvia` INT NOT NULL,
  `idProyectoEnviado` INT NOT NULL,
  `puntaje` DOUBLE NOT NULL DEFAULT 0.0,
  `horaTermino` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idsolucionProyecto`),
  INDEX `usuarioEnvia_idx` (`idUsuarioEnvia` ASC),
  INDEX `proyectoEnvia_idx` (`idProyectoEnviado` ASC),
  CONSTRAINT `usuarioEnvia`
    FOREIGN KEY (`idUsuarioEnvia`)
    REFERENCES `online_judge`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `proyectoEnvia`
    FOREIGN KEY (`idProyectoEnviado`)
    REFERENCES `online_judge`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_judge`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`administrador` (
  `idUsuario` INT NOT NULL,
  `credencial` VARCHAR(45) NOT NULL,
  INDEX `iduserAdmin_idx` (`idUsuario` ASC),
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `iduserAdmin`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `online_judge`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `online_judge`.`concursante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`concursante` (
  `idConcursante` INT NOT NULL,
  `credencial` VARCHAR(45) NOT NULL,
  INDEX `iduserConcursante_idx` (`idConcursante` ASC),
  PRIMARY KEY (`idConcursante`),
  CONSTRAINT `iduserAdmin0`
    FOREIGN KEY (`idConcursante`)
    REFERENCES `online_judge`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `online_judge`.`ejecucionproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`ejecucionproyecto` (
  `idejecucion` INT NOT NULL,
  `idproyecto` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  PRIMARY KEY (`idejecucion`),
  INDEX `idProyecto_idx` (`idproyecto` ASC),
  CONSTRAINT `idProyecto`
    FOREIGN KEY (`idproyecto`)
    REFERENCES `online_judge`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `online_judge`.`ejecucionexamen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`ejecucionexamen` (
  `idejecucion` INT NOT NULL,
  `idexamen` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  PRIMARY KEY (`idejecucion`),
  INDEX `idexamen_idx_fk` (`idexamen` ASC),
  CONSTRAINT `idexamen_fk`
    FOREIGN KEY (`idexamen`)
    REFERENCES `online_judge`.`examen` (`idexamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `online_judge`.`alumno_has_examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`alumno_has_examen` (
  `alumno_idUsuario` INT NOT NULL,
  `examen_idexamen` INT NOT NULL,
  PRIMARY KEY (`alumno_idUsuario`, `examen_idexamen`),
  INDEX `fk_alumno_has_examen_examen1_idx` (`examen_idexamen` ASC),
  INDEX `fk_alumno_has_examen_alumno1_idx` (`alumno_idUsuario` ASC),
  CONSTRAINT `fk_alumno_has_examen_alumno1`
    FOREIGN KEY (`alumno_idUsuario`)
    REFERENCES `online_judge`.`alumno` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_examen_examen1`
    FOREIGN KEY (`examen_idexamen`)
    REFERENCES `online_judge`.`examen` (`idexamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
